### ISSUE TITLE
Needs to depend on OLA>=0.9.6

### ISSUE THREAD

**Issue by peternewman** [OpenLightingProject/ja-rule#54]
Doesn't build with OLA 0.9.5 due to this https://github.com/OpenLightingProject/ola/pull/721#issuecomment-111821811

**Comment by peternewman** [comment]
g++ -DHAVE_CONFIG_H -I.    -I system_config -I harmony/include -I ../firmware/src -Wall -Wformat -W -Werror -I include -fvisibility-inlines-hidden -isystem ../googlemock-read-only/include -isystem ../googlemock-read-only/gtest/include -I ./mocks -I ./harmony/mocks -pthread   -g -O2 -std=c++11 -MT tests/tests_rdm_responder_test-RDMResponderTest.o -MD -MP -MF tests/.deps/tests_rdm_responder_test-RDMResponderTest.Tpo -c -o tests/tests_rdm_responder_test-RDMResponderTest.o `test -f 'tests/RDMResponderTest.cpp' || echo './'`tests/RDMResponderTest.cpp
tests/RDMResponderTest.cpp: In member function ‘void RDMResponderTest::SendRequest(const ola::rdm::RDMRequest*)’:
tests/RDMResponderTest.cpp:125:5: error: ‘ByteString’ is not a member of ‘ola::io’
tests/RDMResponderTest.cpp:125:25: error: expected ‘;’ before ‘data’
tests/RDMResponderTest.cpp:126:5: error: ‘data’ was not declared in this scope
tests/RDMResponderTest.cpp: In member function ‘virtual void RDMResponderTest_invalidCommand_Test::TestBody()’:
tests/RDMResponderTest.cpp:175:60: error: no matching function for call to ‘ola::rdm::BaseRDMRequest<(ola::rdm::RDMCommand::RDMCommandClass)32u>::BaseRDMRequest(ola::rdm::UID&, ola::rdm::UID&, int, int, int, int, NULL, int)’
tests/RDMResponderTest.cpp:175:60: note: candidate is:
In file included from tests/RDMResponderTest.cpp:24:0:
/usr/include/ola/rdm/RDMCommand.h:350:5: note: ola::rdm::BaseRDMRequest<command_class>::BaseRDMRequest(const ola::rdm::UID&, const ola::rdm::UID&, uint8_t, uint8_t, uint8_t, uint16_t, uint16_t, const uint8_t*, unsigned int) [with ola::rdm::RDMCommand::RDMCommandClass command_class = (ola::rdm::RDMCommand::RDMCommandClass)32u; uint8_t = unsigned char; uint16_t = short unsigned int]
/usr/include/ola/rdm/RDMCommand.h:350:5: note:   candidate expects 9 arguments, 8 provided
tests/RDMResponderTest.cpp: In member function ‘virtual void RDMResponderTest_subdeviceNack_Test::TestBody()’:
tests/RDMResponderTest.cpp:312:69: error: no matching function for call to ‘ola::rdm::BaseRDMRequest<(ola::rdm::RDMCommand::RDMCommandClass)32u>::BaseRDMRequest(ola::rdm::UID&, ola::rdm::UID&, int, int, int, RDMPid, NULL, int)’
tests/RDMResponderTest.cpp:312:69: note: candidate is:
In file included from tests/RDMResponderTest.cpp:24:0:
/usr/include/ola/rdm/RDMCommand.h:350:5: note: ola::rdm::BaseRDMRequest<command_class>::BaseRDMRequest(const ola::rdm::UID&, const ola::rdm::UID&, uint8_t, uint8_t, uint8_t, uint16_t, uint16_t, const uint8_t*, unsigned int) [with ola::rdm::RDMCommand::RDMCommandClass command_class = (ola::rdm::RDMCommand::RDMCommandClass)32u; uint8_t = unsigned char; uint16_t = short unsigned int]
/usr/include/ola/rdm/RDMCommand.h:350:5: note:   candidate expects 9 arguments, 8 provided
tests/RDMResponderTest.cpp: In member function ‘virtual void RDMResponderTest_supportedParameters_Test::TestBody()’:
tests/RDMResponderTest.cpp:335:78: error: no matching function for call to ‘ola::rdm::BaseRDMRequest<(ola::rdm::RDMCommand::RDMCommandClass)32u>::BaseRDMRequest(ola::rdm::UID&, ola::rdm::UID&, int, int, int, RDMPid, NULL, int)’
tests/RDMResponderTest.cpp:335:78: note: candidate is:
In file included from tests/RDMResponderTest.cpp:24:0:
/usr/include/ola/rdm/RDMCommand.h:350:5: note: ola::rdm::BaseRDMRequest<command_class>::BaseRDMRequest(const ola::rdm::UID&, const ola::rdm::UID&, uint8_t, uint8_t, uint8_t, uint16_t, uint16_t, const uint8_t*, unsigned int) [with ola::rdm::RDMCommand::RDMCommandClass command_class = (ola::rdm::RDMCommand::RDMCommandClass)32u; uint8_t = unsigned char; uint16_t = short unsigned int]
/usr/include/ola/rdm/RDMCommand.h:350:5: note:   candidate expects 9 arguments, 8 provided
tests/RDMResponderTest.cpp: In member function ‘virtual void RDMResponderTest_deviceInfo_Test::TestBody()’:
tests/RDMResponderTest.cpp:361:69: error: no matching function for call to ‘ola::rdm::BaseRDMRequest<(ola::rdm::RDMCommand::RDMCommandClass)32u>::BaseRDMRequest(ola::rdm::UID&, ola::rdm::UID&, int, int, int, RDMPid, NULL, int)’
tests/RDMResponderTest.cpp:361:69: note: candidate is:
In file included from tests/RDMResponderTest.cpp:24:0:
/usr/include/ola/rdm/RDMCommand.h:350:5: note: ola::rdm::BaseRDMRequest<command_class>::BaseRDMRequest(const ola::rdm::UID&, const ola::rdm::UID&, uint8_t, uint8_t, uint8_t, uint16_t, uint16_t, const uint8_t*, unsigned int) [with ola::rdm::RDMCommand::RDMCommandClass command_class = (ola::rdm::RDMCommand::RDMCommandClass)32u; uint8_t = unsigned char; uint16_t = short unsigned int]
/usr/include/ola/rdm/RDMCommand.h:350:5: note:   candidate expects 9 arguments, 8 provided
tests/RDMResponderTest.cpp: In member function ‘virtual void RDMResponderTest_deviceModelDescription_Test::TestBody()’:
tests/RDMResponderTest.cpp:386:14: error: no matching function for call to ‘ola::rdm::BaseRDMRequest<(ola::rdm::RDMCommand::RDMCommandClass)32u>::BaseRDMRequest(ola::rdm::UID&, ola::rdm::UID&, int, int, int, RDMPid, NULL, int)’
tests/RDMResponderTest.cpp:386:14: note: candidate is:
In file included from tests/RDMResponderTest.cpp:24:0:
/usr/include/ola/rdm/RDMCommand.h:350:5: note: ola::rdm::BaseRDMRequest<command_class>::BaseRDMRequest(const ola::rdm::UID&, const ola::rdm::UID&, uint8_t, uint8_t, uint8_t, uint16_t, uint16_t, const uint8_t*, unsigned int) [with ola::rdm::RDMCommand::RDMCommandClass command_class = (ola::rdm::RDMCommand::RDMCommandClass)32u; uint8_t = unsigned char; uint16_t = short unsigned int]
/usr/include/ola/rdm/RDMCommand.h:350:5: note:   candidate expects 9 arguments, 8 provided
tests/RDMResponderTest.cpp: In member function ‘virtual void RDMResponderTest_manufacturerLabel_Test::TestBody()’:
tests/RDMResponderTest.cpp:412:14: error: no matching function for call to ‘ola::rdm::BaseRDMRequest<(ola::rdm::RDMCommand::RDMCommandClass)32u>::BaseRDMRequest(ola::rdm::UID&, ola::rdm::UID&, int, int, int, RDMPid, NULL, int)’
tests/RDMResponderTest.cpp:412:14: note: candidate is:
In file included from tests/RDMResponderTest.cpp:24:0:
/usr/include/ola/rdm/RDMCommand.h:350:5: note: ola::rdm::BaseRDMRequest<command_class>::BaseRDMRequest(const ola::rdm::UID&, const ola::rdm::UID&, uint8_t, uint8_t, uint8_t, uint16_t, uint16_t, const uint8_t*, unsigned int) [with ola::rdm::RDMCommand::RDMCommandClass command_class = (ola::rdm::RDMCommand::RDMCommandClass)32u; uint8_t = unsigned char; uint16_t = short unsigned int]
/usr/include/ola/rdm/RDMCommand.h:350:5: note:   candidate expects 9 arguments, 8 provided
tests/RDMResponderTest.cpp: In member function ‘virtual void RDMResponderTest_softwareVersionLabel_Test::TestBody()’:
tests/RDMResponderTest.cpp:436:14: error: no matching function for call to ‘ola::rdm::BaseRDMRequest<(ola::rdm::RDMCommand::RDMCommandClass)32u>::BaseRDMRequest(ola::rdm::UID&, ola::rdm::UID&, int, int, int, RDMPid, NULL, int)’
tests/RDMResponderTest.cpp:436:14: note: candidate is:
In file included from tests/RDMResponderTest.cpp:24:0:
/usr/include/ola/rdm/RDMCommand.h:350:5: note: ola::rdm::BaseRDMRequest<command_class>::BaseRDMRequest(const ola::rdm::UID&, const ola::rdm::UID&, uint8_t, uint8_t, uint8_t, uint16_t, uint16_t, const uint8_t*, unsigned int) [with ola::rdm::RDMCommand::RDMCommandClass command_class = (ola::rdm::RDMCommand::RDMCommandClass)32u; uint8_t = unsigned char; uint16_t = short unsigned int]
/usr/include/ola/rdm/RDMCommand.h:350:5: note:   candidate expects 9 arguments, 8 provided
Makefile:1443: recipe for target 'tests/tests_rdm_responder_test-RDMResponderTest.o' failed
make[1]: *** [tests/tests_rdm_responder_test-RDMResponderTest.o] Error 1

**Comment by peternewman** [comment]
I also missed the bigger issue of ByteString!

**Comment by nomis52** [comment]
Yup, ByteString is the big one.

**Comment by peternewman** [comment]
diff --git a/tests/configure.ac b/tests/configure.ac
index 831fa95..ee2a9a4 100644
--- a/tests/configure.ac
+++ b/tests/configure.ac
@@ -94,7 +94,7 @@ AS_IF([test -z "$PKG_CONFIG"],
 # OLA
 PKG_CHECK_MODULES(
   OLA,
-  [libola],
+  [libola >= 0.9.6],
   [],
   [AC_MSG_ERROR([Missing OLA, please install])])
